# Generated by Django 6.0 on 2025-12-13 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
