"""
Django settings for christmas_day project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
import boto3

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# upload keys to AWS parameter store
ssm = boto3.client("ssm", region_name="us-west-1")

SECRET_KEY = ssm.get_parameter(Name="/django-01-tyn/drf", WithDecryption=True)["Parameter"]["Value"]

# set debug to false
DEBUG = True

# change allowed hosts to IP / domain
ALLOWED_HOSTS = [
    "54.215.246.62",
    "thankyounotes.today",
    "www.thankyounotes.today",
    "api.thankyounotes.today"
]


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "sm",
    "rest_framework",
    "corsheaders",
    "storages"
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    "DEFAULT_RENDERER_CLASSES": (
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer" # this allows for navigation to any endpoint from anywhere - security liability in deployment
    )
}

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# cors section (includes above addition to INSTALLED APPS)
CORS_ALLOW_ALL_ORIGINS = False

CORS_ALLOWED_ORIGINS = [
    "http://54.215.246.62",
    "http://thankyounotes.today",
    "http://www.thankyounotes.today",
    "http://api.thankyounotes.today",

    "https://thankyounotes.today",
    "https://www.thankyounotes.today",
    "https://api.thankyounotes.today"
]

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT'
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with'
]

# twilio section, not nee
TWILIO_ACCOUNT_SID = ssm.get_parameter(Name="/django-01-tyn/twilio-sid", WithDecryption=True)["Parameter"]["Value"]
TWILIO_AUTH_TOKEN = ssm.get_parameter(Name="/django-01-tyn/twilio-auth-token", WithDecryption=True)["Parameter"]["Value"]
TWILIO_PHONE_NUMBER = ssm.get_parameter(Name="/django-01-tyn/twilio-phone-number", WithDecryption=True)["Parameter"]["Value"]

ROOT_URLCONF = 'christmas_day.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'christmas_day.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# simple JWT
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=5),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True
}

# add in HTTPS redirect and security hardening
#
#
#
#

# cookie handling (even though JWT is used, this is for the admin portal)
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = False # may need to change this in production
CSRF_COOKIE_SECURE = False # may need to change this in production

CSRF_TRUSTED_ORIGINS = [
    "http://54.215.246.62", 
    "http://thankyounotes.today",
    "http://www.thankyounotes.today"
]



# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'EST'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

# will need to change this in deployment to S3

AWS_ACCESS_KEY_ID = ssm.get_parameter(Name="S3_ACCESS_KEY", WithDecryption=True)["Parameter"]["Value"]
AWS_SECRET_ACCESS_KEY = ssm.get_parameter(Name="S3_SECRET_KEY", WithDecryption=True)["Parameter"]["Value"]

AWS_STORAGE_BUCKET_NAME = "django-01-tyn-s3"
AWS_S3_REGION_NAME = "us-west-1"
AWS_DEFAULT_ACL = "public-read"
AWS_S3_FILE_OVERWRITE = False

DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"

MEDIA_LOCATION = "media"
AWS_LOCATION = MEDIA_LOCATION
MEDIA_URL = f"https://{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com/{MEDIA_LOCATION}/"

# authentication model
AUTH_USER_MODEL = "sm.CustomUser"
